<package format="2">
  <name>s57_grids</name>
  <version>0.0.0</version>
  <description>
    Generate grids from S57 marine chart data
  </description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>
  <author>Roland Arsenault</author>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>geographic_msgs</depend>
  <depend>grid_map_ros</depend>
  <depend>lifecycle_msgs</depend>
  <depend>marine_charts</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>s57_msgs</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
